# Generated by Django 3.0.3 on 2020-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostsAllow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('mac_addr', models.CharField(max_length=17)),
                ('ip_addr', models.GenericIPAddressField(protocol='IPv4')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subnets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ip_subnet', models.GenericIPAddressField(protocol='IPv4')),
                ('mask_subnet', models.GenericIPAddressField(protocol='IPv4')),
                ('gw_subnet', models.GenericIPAddressField(protocol='IPv4')),
                ('ip_start', models.GenericIPAddressField(protocol='IPv4')),
                ('ip_end', models.GenericIPAddressField(protocol='IPv4')),
                ('ip_broadcast', models.GenericIPAddressField(protocol='IPv4')),
                ('dns_prefix', models.CharField(default='eltex.local', max_length=30)),
                ('dns_main', models.GenericIPAddressField(default='10.22.0.3', protocol='IPv4')),
                ('dns_res', models.GenericIPAddressField(default='', protocol='IPv4')),
            ],
        ),
    ]
