# Generated by Django 3.0.3 on 2020-02-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostsAllow',
            new_name='Hosts_Allow',
        ),
    ]
