# Generated by Django 3.0.3 on 2020-02-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0002_auto_20200227_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts_allow',
            options={'verbose_name_plural': 'Доступные/Зарезервированные ip'},
        ),
        migrations.AlterModelOptions(
            name='subnets',
            options={'verbose_name_plural': 'Подсети'},
        ),
        migrations.AlterField(
            model_name='subnets',
            name='dns_res',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
