# Generated by Django 3.0.3 on 2020-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0003_auto_20200228_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnets',
            name='dns_res',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
