# Generated by Django 3.0.3 on 2020-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0005_auto_20200228_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts_allow',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
