# Generated by Django 3.0.3 on 2020-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0006_auto_20200228_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts_allow',
            options={'verbose_name': '"Доступные/Зарезервированные ip"', 'verbose_name_plural': 'Доступные/Зарезервированные ip'},
        ),
        migrations.AlterModelOptions(
            name='subnets',
            options={'verbose_name': '"Подсеть"', 'verbose_name_plural': 'Подсети'},
        ),
        migrations.AlterField(
            model_name='hosts_allow',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hosts_allow',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='Имя хоста'),
        ),
        migrations.AlterField(
            model_name='hosts_allow',
            name='ip_addr',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='ip адрес'),
        ),
        migrations.AlterField(
            model_name='hosts_allow',
            name='mac_addr',
            field=models.CharField(max_length=17, verbose_name='mac адрес'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='dns_main',
            field=models.GenericIPAddressField(default='10.22.0.3', protocol='IPv4', verbose_name='Осн. dns сервер'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='dns_prefix',
            field=models.CharField(default='eltex.local', max_length=30, verbose_name='dns префикс'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='dns_res',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Резерв. dns сервер'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='gw_subnet',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Маска Подсети'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='ip_broadcast',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Широковещательный адрес'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='ip_end',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='ip конечный'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='ip_start',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='ip начальный'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='ip_subnet',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='mask_subnet',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='ip адрес'),
        ),
    ]
