# Generated by Django 3.0.3 on 2020-03-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0009_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='File_Upload',
        ),
    ]
