# Generated by Django 3.0.3 on 2020-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0010_auto_20200313_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='File_Upload',
        ),
    ]
