# Generated by Django 3.0.3 on 2020-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0011_auto_20200313_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='file_obj',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
