# Generated by Django 3.0.3 on 2020-03-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0012_auto_20200313_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
