# Generated by Django 3.0.3 on 2020-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0013_delete_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='media/upload/')),
            ],
        ),
    ]
