# Generated by Django 3.0.3 on 2020-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0014_csv_parser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_parser',
            name='file_field',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
