# Generated by Django 3.0.3 on 2020-03-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0015_auto_20200316_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv_Parser',
        ),
    ]
