# Generated by Django 3.0.3 on 2020-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0016_delete_csv_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
