# Generated by Django 3.0.3 on 2020-03-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0017_csv_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv_File',
        ),
    ]
