# Generated by Django 3.0.3 on 2020-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0019_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_obj',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
