# Generated by Django 3.0.3 on 2020-03-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0021_auto_20200316_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
