# Generated by Django 3.0.3 on 2020-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_dhcpmanager', '0023_auto_20200317_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts_allow',
            options={'ordering': ['id'], 'verbose_name': '"Доступные/Зарезервированные ip"', 'verbose_name_plural': 'Доступные/Зарезервированные ip'},
        ),
    ]
